spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

server:
  port: 8083

kinesis:
  stream-name: ${KINESIS_STREAM_NAME:}

aws:
  region: ${AWS_REGION:us-east-1}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
